"""
reporting/reporter.py — Generates reports as strings/dicts (v2: no file I/O, API serves them).
"""

import datetime
import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from scanner.async_engine import ScanResult

_SEV_COLOR = {
    "CRITICAL": "#dc2626", "HIGH": "#ea580c",
    "MEDIUM": "#d97706", "LOW": "#2563eb", "INFO": "#6b7280",
}
_SEV_EMOJI = {
    "CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵", "INFO": "⚪",
}


class Reporter:
    def __init__(self, result: "ScanResult"):
        self.result = result
        self._ts    = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        # Normalise findings to dicts
        self._findings = [
            f if isinstance(f, dict) else f.to_dict()
            for f in result.findings
        ]

    def export_json_dict(self) -> dict:
        return {
            "meta": {
                "tool": "WebScan v2", "generated": self._ts,
                "target": self.result.target, "duration_s": self.result.duration_s,
            },
            "summary": self._summary(),
            "findings": self._findings,
            "errors":   self.result.errors,
        }

    def export_markdown_str(self) -> str:
        lines = [
            f"# WebScan Security Report\n",
            f"**Target:** `{self.result.target}`  ",
            f"**Generated:** {self._ts}  ",
            "**CONFIDENTIAL — AUTHORIZED TESTING ONLY**\n",
            "---\n## Summary\n",
            "| Key | Value |", "|-----|-------|",
            f"| Pages crawled | {self.result.pages_crawled} |",
            f"| Duration | {self.result.duration_s}s |",
            f"| Total findings | {len(self._findings)} |",
            "",
            "| Severity | Count |", "|----------|-------|",
        ]
        s = self._summary()
        for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
            lines.append(f"| {_SEV_EMOJI[sev]} {sev} | {s['by_severity'].get(sev, 0)} |")
        lines.append("")

        by_sev: dict[str, list] = {}
        for f in self._findings:
            by_sev.setdefault(f["severity"], []).append(f)

        for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
            group = by_sev.get(sev, [])
            if not group:
                continue
            lines.append(f"\n## {_SEV_EMOJI[sev]} {sev} ({len(group)})\n")
            for i, f in enumerate(group, 1):
                lines += [
                    f"### {i}. {f['vuln_type']}",
                    f"| Field | Value |", "|-------|-------|",
                    f"| URL | `{f['url']}` |",
                    f"| Parameter | `{f['param']}` |",
                    f"| Method | {f['method']} |",
                    f"| CWE | {f.get('cwe') or 'N/A'} |",
                    f"| Confidence | {f.get('confidence', 'N/A')} |",
                    "",
                    f"**Description:** {f['description']}\n",
                    f"**Indicator:** `{f['response_indicator']}`\n",
                    f"**Mitigation:** {f['mitigation']}\n",
                    "---",
                ]
        lines.append("\n*Generated by WebScan v2 — authorized testing only.*")
        return "\n".join(lines)

    def export_html_str(self) -> str:
        s          = self._summary()
        ts         = self._ts
        finding_html = "".join(self._html_finding(f) for f in self._findings)

        sev_pills = "".join(
            f'<span class="pill" style="background:{_SEV_COLOR[sev]}">'
            f'{s["by_severity"].get(sev,0)} {sev}</span>'
            for sev in ["CRITICAL","HIGH","MEDIUM","LOW","INFO"]
            if s["by_severity"].get(sev,0)
        )

        return f"""<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>WebScan Report — {_esc(self.result.target)}</title>
<style>
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:'Segoe UI',system-ui,sans-serif;background:#0f1117;color:#e2e8f0;line-height:1.6}}
.header{{background:#161b27;border-bottom:1px solid #1e293b;padding:1.5rem 2rem;display:flex;align-items:center;gap:1rem}}
.header h1{{font-size:1.4rem;color:#f8fafc;font-weight:600}}
.badge-conf{{background:#dc2626;color:#fff;font-size:.7rem;padding:2px 8px;border-radius:3px;letter-spacing:.08em}}
.container{{max-width:1100px;margin:0 auto;padding:2rem}}
.meta-bar{{display:flex;gap:2rem;flex-wrap:wrap;margin-bottom:2rem;padding:1rem 1.5rem;background:#161b27;border-radius:10px;border:1px solid #1e293b}}
.meta-bar .stat{{display:flex;flex-direction:column;gap:2px}}
.meta-bar .stat .label{{font-size:.72rem;text-transform:uppercase;letter-spacing:.06em;color:#64748b}}
.meta-bar .stat .value{{font-size:1.6rem;font-weight:700;color:#f8fafc}}
.pills{{display:flex;flex-wrap:wrap;gap:.5rem;margin-bottom:1.5rem}}
.pill{{font-size:.75rem;font-weight:700;padding:4px 10px;border-radius:20px;color:#fff;letter-spacing:.04em}}
h2{{font-size:1.1rem;color:#94a3b8;margin:2rem 0 1rem;text-transform:uppercase;letter-spacing:.06em;font-weight:500}}
.finding{{background:#161b27;border:1px solid #1e293b;border-radius:10px;margin-bottom:1rem;overflow:hidden}}
.finding-top{{display:flex;align-items:center;gap:.75rem;padding:.9rem 1.25rem;border-left:4px solid currentColor}}
.severity-badge{{font-size:.7rem;font-weight:700;padding:3px 8px;border-radius:4px;color:#fff;letter-spacing:.05em}}
.finding-title{{font-weight:600;font-size:.95rem;color:#f1f5f9}}
.finding-body{{padding:1rem 1.25rem}}
.meta-table{{width:100%;border-collapse:collapse;font-size:.84rem;margin:.5rem 0}}
.meta-table td{{padding:.3rem .5rem;border-bottom:1px solid #1e293b;color:#cbd5e1}}
.meta-table td:first-child{{color:#64748b;width:140px;font-weight:500}}
.label-section{{font-size:.7rem;text-transform:uppercase;letter-spacing:.07em;color:#475569;margin:.75rem 0 .25rem}}
.description{{font-size:.88rem;color:#94a3b8;margin-bottom:.5rem}}
pre{{background:#0a0d14;border:1px solid #1e293b;border-radius:6px;padding:.75rem;font-size:.8rem;color:#86efac;overflow-x:auto;white-space:pre-wrap;word-break:break-all}}
.mitigation{{background:#0f2820;border-left:3px solid #16a34a;border-radius:0 6px 6px 0;padding:.7rem 1rem;font-size:.86rem;color:#86efac;margin-top:.75rem}}
footer{{text-align:center;font-size:.75rem;color:#334155;padding:2rem}}
</style></head><body>
<div class="header">
  <div>
    <h1>⚡ WebScan Security Report</h1>
    <div style="font-size:.8rem;color:#64748b;margin-top:2px">{_esc(self.result.target)} · {ts}</div>
  </div>
  <span class="badge-conf">CONFIDENTIAL</span>
</div>
<div class="container">
  <div class="meta-bar">
    <div class="stat"><span class="label">Findings</span><span class="value">{len(self._findings)}</span></div>
    <div class="stat"><span class="label">Pages</span><span class="value">{self.result.pages_crawled}</span></div>
    <div class="stat"><span class="label">Duration</span><span class="value">{self.result.duration_s}s</span></div>
    <div class="stat"><span class="label">Vectors tested</span><span class="value">{self.result.input_vectors}</span></div>
  </div>
  <div class="pills">{sev_pills}</div>
  <h2>Vulnerability Findings</h2>
  {finding_html or '<p style="color:#475569">No vulnerabilities detected.</p>'}
</div>
<footer>WebScan v2 — Authorized testing environments only.</footer>
</body></html>"""

    def _summary(self) -> dict:
        by_sev: dict[str, int] = {}
        for f in self._findings:
            by_sev[f["severity"]] = by_sev.get(f["severity"], 0) + 1
        return {
            "total": len(self._findings),
            "pages_crawled": self.result.pages_crawled,
            "duration_s": self.result.duration_s,
            "by_severity": by_sev,
        }

    @staticmethod
    def _html_finding(f: dict) -> str:
        color   = _SEV_COLOR.get(f["severity"], "#6b7280")
        snippet = (
            f'<div class="label-section">Evidence</div><pre>{_esc(f.get("evidence_snippet",""))}</pre>'
            if f.get("evidence_snippet") else ""
        )
        req_ex  = (
            f'<div class="label-section">Request</div><pre>{_esc(f.get("request_example",""))}</pre>'
            if f.get("request_example") else ""
        )
        return f"""<div class="finding">
<div class="finding-top" style="color:{color}">
  <span class="severity-badge" style="background:{color}">{_esc(f['severity'])}</span>
  <span class="finding-title">{_esc(f['vuln_type'])}</span>
</div>
<div class="finding-body">
  <table class="meta-table">
    <tr><td>URL</td><td><code>{_esc(f['url'])}</code></td></tr>
    <tr><td>Parameter</td><td><code>{_esc(f['param'])}</code></td></tr>
    <tr><td>Method</td><td>{_esc(f['method'])}</td></tr>
    <tr><td>CWE</td><td>{_esc(f.get('cwe') or 'N/A')}</td></tr>
    <tr><td>Confidence</td><td>{_esc(f.get('confidence','N/A'))}</td></tr>
    <tr><td>Indicator</td><td><code>{_esc(f.get('response_indicator',''))}</code></td></tr>
  </table>
  <div class="label-section">Description</div>
  <div class="description">{_esc(f.get('description',''))}</div>
  {snippet}{req_ex}
  <div class="mitigation"><strong>Mitigation:</strong> {_esc(f.get('mitigation',''))}</div>
</div></div>"""


def _esc(s: str) -> str:
    return (s or "").replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")
